### ISSUE TITLE
imwatermark

### ISSUE THREAD

**Issue by geowjm** [jquesnelle/txt2imghd#14]
Traceback (most recent call last):
  File "scripts/txt2imghd.py", line 13, in <module>
    from imwatermark import WatermarkEncoder
ModuleNotFoundError: No module named 'imwatermark'

what am i doing wrong?

**Comment by parsec501** [comment]
Have you activated the environment?

If so, try `pip install imWatermark`

**Comment by jnpatrick99** [comment]
Didn't help me! This doesn't work, asks for `imwatermark` even after installing it with pip. I did install stable and did activated `ldm`. Probably some environment issue?
