### ISSUE TITLE
ImportError: cannot import name 'WatermarkEncoder' from 'imWatermark'

### ISSUE THREAD

**Issue by crypto-pea** [jquesnelle/txt2imghd#17]
I think I'm doing something wrong?

I get an error message: 
_ImportError: cannot import name 'WatermarkEncoder' from 'imWatermark' (C:\Users\XXX\\.conda\envs\ldm\lib\site-packages\imWatermark.py)_
"scripts/txt2img.py", line 8

**Comment by nerdyrodent** [comment]
You need to install stable diffusion first, then you can run this script which is called ```txt2imghd.py```

**Comment by jnpatrick99** [comment]
Didn't help me! This doesn't work, asks for `imwatermark` even after installing it with pip. I did install stable and did activated `ldm`. Probably some environment issue?
