### ISSUE TITLE
Is it possible to do the detailing passes with SD but not use ESRGAN?

### ISSUE THREAD

**Issue by benedlore** [jquesnelle/txt2imghd#35]
I find myself in a situation where I want to basically skip the ESRGAN step, but still do the detailing and blending together of SD on the image. Is there an argument that allows me to skip the ESRGAN upscaling?

**Comment by RedmondHosting** [comment]
Could you just do a bicubic scaling with PIL or something? Is ESRGAN you think removing too much detail?

**Comment by benedlore** [comment]
Yea, exactly. Since that post I have found other ways to do it, pretty much just like you said along with using other models other than ESRGAN to do the initial upscaling with better results (the web ui makes testing all sorts of different upscaling models really easy for this kind of upscaling).
