### ISSUE TITLE
Upscale a selected input image?

### ISSUE THREAD

**Issue by KenLubin** [jquesnelle/txt2imghd#8]
I wonder is it possible to do the upscaling for a selected input image? I want to quickly generate a big batch with my usual script and then upscale the selected images with yours.

edit: I managed to make it work by making this edit:

`base_filename = f"input"`        

So it generates its own image, saves it, and then takes input.png that I put and upscales it. It still generates the first image, but it works. I don't know any programming language, just figured this out using logic, couldn't figure out how to stop it from generating the first image.

Would love for someone with actual knowledge to write a more efficient script, though, because the results are amazing.

**Comment by parsec501** [comment]
https://github.com/jquesnelle/txt2imghd/pull/11
